# Generated by Django 4.2 on 2023-04-07 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0002_alter_season_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='episode.season'),
        ),
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
