# Generated by Django 4.2 on 2023-04-08 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
        ('episode', '0004_rename_author_like_user_playlistbase_musicplaylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='episode.episode')),
            ],
        ),
        migrations.RenameModel(
            old_name='PlaylistBase',
            new_name='Playlist',
        ),
        migrations.DeleteModel(
            name='MusicPlaylist',
        ),
        migrations.AddField(
            model_name='playlistitems',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='episode.playlist'),
        ),
    ]
